# This is the minimal configuration to directly start a pre-configured server in sandbox mode.
# Simply run 'docker-compose up -d', you can log in with admin/admin at https://localhost:8080 
# After accepting the self signed certificate

# Adapt to your convenience and report to the documentation to explore further possibilities.

# WebUI Admin definition
frontendlogin: admin
frontendpassword: admin

# DB connection
dbconnectiontype: tcp
dbtcphostname: mysql
dbtcpport: 3306
dbtcpname: cells
dbtcpuser: cells
dbtcppassword: cells

# Mongo Setup
documentsdsn: mongodb://mongo:27017/cells
usedocumentsdsn: true

# Advanced Datasource Setup 
dstype: S3
dss3custom: http://minio-ha:9000?minio=true
dss3apikey: minioadminuser
dss3apisecret: minioadminkey
dss3bucketdefault: pydiods1
dss3bucketpersonal: personal
dss3bucketcells: cellsdata
dss3bucketbinaries: binaries
dss3bucketthumbs: thumbnails
dss3bucketversions: versions
